// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChUpdateResponder is an autogenerated mock type for the ChUpdateResponder type
type ChUpdateResponder struct {
	mock.Mock
}

// Accept provides a mock function with given fields: ctx
func (_m *ChUpdateResponder) Accept(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reject provides a mock function with given fields: ctx, reason
func (_m *ChUpdateResponder) Reject(ctx context.Context, reason string) error {
	ret := _m.Called(ctx, reason)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
