// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	peer "perun.network/go-perun/peer"
)

// CommBackend is an autogenerated mock type for the CommBackend type
type CommBackend struct {
	mock.Mock
}

// NewDialer provides a mock function with given fields:
func (_m *CommBackend) NewDialer() peer.Dialer {
	ret := _m.Called()

	var r0 peer.Dialer
	if rf, ok := ret.Get(0).(func() peer.Dialer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peer.Dialer)
		}
	}

	return r0
}

// NewListener provides a mock function with given fields: address
func (_m *CommBackend) NewListener(address string) (peer.Listener, error) {
	ret := _m.Called(address)

	var r0 peer.Listener
	if rf, ok := ret.Get(0).(func(string) peer.Listener); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peer.Listener)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
