// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	peer "perun.network/go-perun/peer"

	wallet "perun.network/go-perun/wallet"
)

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Dialer) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dial provides a mock function with given fields: ctx, addr
func (_m *Dialer) Dial(ctx context.Context, addr wallet.Address) (peer.Conn, error) {
	ret := _m.Called(ctx, addr)

	var r0 peer.Conn
	if rf, ok := ret.Get(0).(func(context.Context, wallet.Address) peer.Conn); ok {
		r0 = rf(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(peer.Conn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, wallet.Address) error); ok {
		r1 = rf(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
