// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	wire "perun.network/go-perun/wire"
)

// Registerer is an autogenerated mock type for the Registerer type
type Registerer struct {
	mock.Mock
}

// Register provides a mock function with given fields: offChainAddr, commAddr
func (_m *Registerer) Register(offChainAddr wire.Address, commAddr string) {
	_m.Called(offChainAddr, commAddr)
}

type mockConstructorTestingTNewRegisterer interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegisterer creates a new instance of Registerer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegisterer(t mockConstructorTestingTNewRegisterer) *Registerer {
	mock := &Registerer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
