// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	wallet "perun.network/go-perun/wallet"
)

// Registerer is an autogenerated mock type for the Registerer type
type Registerer struct {
	mock.Mock
}

// Register provides a mock function with given fields: offChainAddr, commAddr
func (_m *Registerer) Register(offChainAddr wallet.Address, commAddr string) {
	_m.Called(offChainAddr, commAddr)
}
