// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	channel "perun.network/go-perun/channel"

	wallet "perun.network/go-perun/wallet"
)

// ROContractRegistry is an autogenerated mock type for the ROContractRegistry type
type ROContractRegistry struct {
	mock.Mock
}

// Adjudicator provides a mock function with given fields:
func (_m *ROContractRegistry) Adjudicator() wallet.Address {
	ret := _m.Called()

	var r0 wallet.Address
	if rf, ok := ret.Get(0).(func() wallet.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wallet.Address)
		}
	}

	return r0
}

// Asset provides a mock function with given fields: symbol
func (_m *ROContractRegistry) Asset(symbol string) (channel.Asset, bool) {
	ret := _m.Called(symbol)

	var r0 channel.Asset
	if rf, ok := ret.Get(0).(func(string) channel.Asset); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(channel.Asset)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// AssetETH provides a mock function with given fields:
func (_m *ROContractRegistry) AssetETH() wallet.Address {
	ret := _m.Called()

	var r0 wallet.Address
	if rf, ok := ret.Get(0).(func() wallet.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wallet.Address)
		}
	}

	return r0
}

// Assets provides a mock function with given fields:
func (_m *ROContractRegistry) Assets() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// Symbol provides a mock function with given fields: asset
func (_m *ROContractRegistry) Symbol(asset channel.Asset) (string, bool) {
	ret := _m.Called(asset)

	var r0 string
	if rf, ok := ret.Get(0).(func(channel.Asset) string); ok {
		r0 = rf(asset)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(channel.Asset) bool); ok {
		r1 = rf(asset)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Token provides a mock function with given fields: symbol
func (_m *ROContractRegistry) Token(symbol string) (wallet.Address, bool) {
	ret := _m.Called(symbol)

	var r0 wallet.Address
	if rf, ok := ret.Get(0).(func(string) wallet.Address); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(wallet.Address)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

type mockConstructorTestingTNewROContractRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewROContractRegistry creates a new instance of ROContractRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewROContractRegistry(t mockConstructorTestingTNewROContractRegistry) *ROContractRegistry {
	mock := &ROContractRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
