// Code generated by mockery v1.0.0. DO NOT EDIT.

package channel

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// mockClock is an autogenerated mock type for the mockClock type
type mockClock struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *mockClock) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// SetLocation provides a mock function with given fields: _a0
func (_m *mockClock) SetLocation(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
