// Copyright (c) 2023 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/hyperledger-labs/perun-node
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: api_messages.proto

// Package pb contains proto3 definitions for user API and the corresponding
// generated code for grpc server and client.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This type is defined as the enumeration of all messages in funding and
// watching service, in order to be able to parse the messages in api/tcp
// package.
type APIMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*APIMessage_FundReq
	//	*APIMessage_FundResp
	//	*APIMessage_RegisterReq
	//	*APIMessage_RegisterResp
	//	*APIMessage_WithdrawReq
	//	*APIMessage_WithdrawResp
	//	*APIMessage_StartWatchingLedgerChannelReq
	//	*APIMessage_StopWatchingReq
	Msg isAPIMessage_Msg `protobuf_oneof:"msg"`
}

func (x *APIMessage) Reset() {
	*x = APIMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIMessage) ProtoMessage() {}

func (x *APIMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIMessage.ProtoReflect.Descriptor instead.
func (*APIMessage) Descriptor() ([]byte, []int) {
	return file_api_messages_proto_rawDescGZIP(), []int{0}
}

func (m *APIMessage) GetMsg() isAPIMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *APIMessage) GetFundReq() *FundReq {
	if x, ok := x.GetMsg().(*APIMessage_FundReq); ok {
		return x.FundReq
	}
	return nil
}

func (x *APIMessage) GetFundResp() *FundResp {
	if x, ok := x.GetMsg().(*APIMessage_FundResp); ok {
		return x.FundResp
	}
	return nil
}

func (x *APIMessage) GetRegisterReq() *RegisterReq {
	if x, ok := x.GetMsg().(*APIMessage_RegisterReq); ok {
		return x.RegisterReq
	}
	return nil
}

func (x *APIMessage) GetRegisterResp() *RegisterResp {
	if x, ok := x.GetMsg().(*APIMessage_RegisterResp); ok {
		return x.RegisterResp
	}
	return nil
}

func (x *APIMessage) GetWithdrawReq() *WithdrawReq {
	if x, ok := x.GetMsg().(*APIMessage_WithdrawReq); ok {
		return x.WithdrawReq
	}
	return nil
}

func (x *APIMessage) GetWithdrawResp() *WithdrawResp {
	if x, ok := x.GetMsg().(*APIMessage_WithdrawResp); ok {
		return x.WithdrawResp
	}
	return nil
}

func (x *APIMessage) GetStartWatchingLedgerChannelReq() *StartWatchingLedgerChannelReq {
	if x, ok := x.GetMsg().(*APIMessage_StartWatchingLedgerChannelReq); ok {
		return x.StartWatchingLedgerChannelReq
	}
	return nil
}

func (x *APIMessage) GetStopWatchingReq() *StopWatchingReq {
	if x, ok := x.GetMsg().(*APIMessage_StopWatchingReq); ok {
		return x.StopWatchingReq
	}
	return nil
}

type isAPIMessage_Msg interface {
	isAPIMessage_Msg()
}

type APIMessage_FundReq struct {
	FundReq *FundReq `protobuf:"bytes,1,opt,name=fund_req,json=fundReq,proto3,oneof"`
}

type APIMessage_FundResp struct {
	FundResp *FundResp `protobuf:"bytes,2,opt,name=fund_resp,json=fundResp,proto3,oneof"`
}

type APIMessage_RegisterReq struct {
	RegisterReq *RegisterReq `protobuf:"bytes,3,opt,name=register_req,json=registerReq,proto3,oneof"`
}

type APIMessage_RegisterResp struct {
	RegisterResp *RegisterResp `protobuf:"bytes,4,opt,name=register_resp,json=registerResp,proto3,oneof"`
}

type APIMessage_WithdrawReq struct {
	WithdrawReq *WithdrawReq `protobuf:"bytes,5,opt,name=withdraw_req,json=withdrawReq,proto3,oneof"`
}

type APIMessage_WithdrawResp struct {
	WithdrawResp *WithdrawResp `protobuf:"bytes,6,opt,name=withdraw_resp,json=withdrawResp,proto3,oneof"`
}

type APIMessage_StartWatchingLedgerChannelReq struct {
	StartWatchingLedgerChannelReq *StartWatchingLedgerChannelReq `protobuf:"bytes,7,opt,name=start_watching_ledger_channel_req,json=startWatchingLedgerChannelReq,proto3,oneof"`
}

type APIMessage_StopWatchingReq struct {
	StopWatchingReq *StopWatchingReq `protobuf:"bytes,8,opt,name=stop_watching_req,json=stopWatchingReq,proto3,oneof"`
}

func (*APIMessage_FundReq) isAPIMessage_Msg() {}

func (*APIMessage_FundResp) isAPIMessage_Msg() {}

func (*APIMessage_RegisterReq) isAPIMessage_Msg() {}

func (*APIMessage_RegisterResp) isAPIMessage_Msg() {}

func (*APIMessage_WithdrawReq) isAPIMessage_Msg() {}

func (*APIMessage_WithdrawResp) isAPIMessage_Msg() {}

func (*APIMessage_StartWatchingLedgerChannelReq) isAPIMessage_Msg() {}

func (*APIMessage_StopWatchingReq) isAPIMessage_Msg() {}

var File_api_messages_proto protoreflect.FileDescriptor

var file_api_messages_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x15, 0x66, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x16, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x03, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x72,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x75,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x07, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x2b, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x48, 0x00, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a,
	0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x48, 0x00, 0x52, 0x0c,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x0c,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52,
	0x65, 0x71, 0x12, 0x37, 0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x48, 0x00, 0x52, 0x0c, 0x77,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x6d, 0x0a, 0x21, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x71,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x1d, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x11, 0x73, 0x74,
	0x6f, 0x70, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x74,
	0x6f, 0x70, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_messages_proto_rawDescOnce sync.Once
	file_api_messages_proto_rawDescData = file_api_messages_proto_rawDesc
)

func file_api_messages_proto_rawDescGZIP() []byte {
	file_api_messages_proto_rawDescOnce.Do(func() {
		file_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_messages_proto_rawDescData)
	})
	return file_api_messages_proto_rawDescData
}

var file_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_messages_proto_goTypes = []interface{}{
	(*APIMessage)(nil),                    // 0: pb.APIMessage
	(*FundReq)(nil),                       // 1: pb.FundReq
	(*FundResp)(nil),                      // 2: pb.FundResp
	(*RegisterReq)(nil),                   // 3: pb.RegisterReq
	(*RegisterResp)(nil),                  // 4: pb.RegisterResp
	(*WithdrawReq)(nil),                   // 5: pb.WithdrawReq
	(*WithdrawResp)(nil),                  // 6: pb.WithdrawResp
	(*StartWatchingLedgerChannelReq)(nil), // 7: pb.StartWatchingLedgerChannelReq
	(*StopWatchingReq)(nil),               // 8: pb.StopWatchingReq
}
var file_api_messages_proto_depIdxs = []int32{
	1, // 0: pb.APIMessage.fund_req:type_name -> pb.FundReq
	2, // 1: pb.APIMessage.fund_resp:type_name -> pb.FundResp
	3, // 2: pb.APIMessage.register_req:type_name -> pb.RegisterReq
	4, // 3: pb.APIMessage.register_resp:type_name -> pb.RegisterResp
	5, // 4: pb.APIMessage.withdraw_req:type_name -> pb.WithdrawReq
	6, // 5: pb.APIMessage.withdraw_resp:type_name -> pb.WithdrawResp
	7, // 6: pb.APIMessage.start_watching_ledger_channel_req:type_name -> pb.StartWatchingLedgerChannelReq
	8, // 7: pb.APIMessage.stop_watching_req:type_name -> pb.StopWatchingReq
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_messages_proto_init() }
func file_api_messages_proto_init() {
	if File_api_messages_proto != nil {
		return
	}
	file_funding_service_proto_init()
	file_watching_service_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*APIMessage_FundReq)(nil),
		(*APIMessage_FundResp)(nil),
		(*APIMessage_RegisterReq)(nil),
		(*APIMessage_RegisterResp)(nil),
		(*APIMessage_WithdrawReq)(nil),
		(*APIMessage_WithdrawResp)(nil),
		(*APIMessage_StartWatchingLedgerChannelReq)(nil),
		(*APIMessage_StopWatchingReq)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_messages_proto_goTypes,
		DependencyIndexes: file_api_messages_proto_depIdxs,
		MessageInfos:      file_api_messages_proto_msgTypes,
	}.Build()
	File_api_messages_proto = out.File
	file_api_messages_proto_rawDesc = nil
	file_api_messages_proto_goTypes = nil
	file_api_messages_proto_depIdxs = nil
}
