// Copyright (c) 2020 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/hyperledger-labs/perun-node
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: errors.proto

// Package pb contains proto3 definitions for user API and the corresponding
// generated code for grpc server and client.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCategory int32

const (
	ErrorCategory_ParticipantError ErrorCategory = 0
	ErrorCategory_ClientError      ErrorCategory = 1
	ErrorCategory_ProtocolError    ErrorCategory = 2
	ErrorCategory_InternalError    ErrorCategory = 3
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ParticipantError",
		1: "ClientError",
		2: "ProtocolError",
		3: "InternalError",
	}
	ErrorCategory_value = map[string]int32{
		"ParticipantError": 0,
		"ClientError":      1,
		"ProtocolError":    2,
		"InternalError":    3,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	// Though "0" is an invalid error code, we still define it, because
	// proto3 requires that every enum definition should have 0 mapped to
	// atleast one constant.
	ErrorCode_DefaultInvalidCode      ErrorCode = 0
	ErrorCode_ErrPeerRequestTimedOut  ErrorCode = 101
	ErrorCode_ErrPeerRejected         ErrorCode = 102
	ErrorCode_ErrPeerNotFunded        ErrorCode = 103
	ErrorCode_ErrUserResponseTimedOut ErrorCode = 104
	ErrorCode_ErrResourceNotFound     ErrorCode = 201
	ErrorCode_ErrResourceExists       ErrorCode = 202
	ErrorCode_ErrInvalidArgument      ErrorCode = 203
	ErrorCode_ErrFailedPreCondition   ErrorCode = 204
	ErrorCode_ErrInvalidConfig        ErrorCode = 205
	ErrorCode_ErrInvalidContracts     ErrorCode = 206
	ErrorCode_ErrTxTimedOut           ErrorCode = 301
	ErrorCode_ErrChainNotReachable    ErrorCode = 302
	ErrorCode_ErrUnknownInternal      ErrorCode = 401
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "DefaultInvalidCode",
		101: "ErrPeerRequestTimedOut",
		102: "ErrPeerRejected",
		103: "ErrPeerNotFunded",
		104: "ErrUserResponseTimedOut",
		201: "ErrResourceNotFound",
		202: "ErrResourceExists",
		203: "ErrInvalidArgument",
		204: "ErrFailedPreCondition",
		205: "ErrInvalidConfig",
		206: "ErrInvalidContracts",
		301: "ErrTxTimedOut",
		302: "ErrChainNotReachable",
		401: "ErrUnknownInternal",
	}
	ErrorCode_value = map[string]int32{
		"DefaultInvalidCode":      0,
		"ErrPeerRequestTimedOut":  101,
		"ErrPeerRejected":         102,
		"ErrPeerNotFunded":        103,
		"ErrUserResponseTimedOut": 104,
		"ErrResourceNotFound":     201,
		"ErrResourceExists":       202,
		"ErrInvalidArgument":      203,
		"ErrFailedPreCondition":   204,
		"ErrInvalidConfig":        205,
		"ErrInvalidContracts":     206,
		"ErrTxTimedOut":           301,
		"ErrChainNotReachable":    302,
		"ErrUnknownInternal":      401,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1}
}

type MsgError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category ErrorCategory `protobuf:"varint,1,opt,name=category,proto3,enum=pb.ErrorCategory" json:"category,omitempty"`
	Code     ErrorCode     `protobuf:"varint,2,opt,name=code,proto3,enum=pb.ErrorCode" json:"code,omitempty"`
	Message  string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are assignable to AddInfo:
	//
	//	*MsgError_ErrInfoPeerRequestTimedOut
	//	*MsgError_ErrInfoPeerRejected
	//	*MsgError_ErrInfoPeerNotFunded
	//	*MsgError_ErrInfoUserResponseTimedOut
	//	*MsgError_ErrInfoResourceNotFound
	//	*MsgError_ErrInfoResourceExists
	//	*MsgError_ErrInfoInvalidArgument
	//	*MsgError_ErrInfoFailedPreCondUnclosedChs
	//	*MsgError_ErrInfoInvalidConfig
	//	*MsgError_ErrInfoInvalidContracts
	//	*MsgError_ErrInfoTxTimedOut
	//	*MsgError_ErrInfoChainNotReachable
	AddInfo isMsgError_AddInfo `protobuf_oneof:"addInfo"`
}

func (x *MsgError) Reset() {
	*x = MsgError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgError) ProtoMessage() {}

func (x *MsgError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgError.ProtoReflect.Descriptor instead.
func (*MsgError) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *MsgError) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ParticipantError
}

func (x *MsgError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_DefaultInvalidCode
}

func (x *MsgError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (m *MsgError) GetAddInfo() isMsgError_AddInfo {
	if m != nil {
		return m.AddInfo
	}
	return nil
}

func (x *MsgError) GetErrInfoPeerRequestTimedOut() *ErrInfoPeerRequestTimedOut {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoPeerRequestTimedOut); ok {
		return x.ErrInfoPeerRequestTimedOut
	}
	return nil
}

func (x *MsgError) GetErrInfoPeerRejected() *ErrInfoPeerRejected {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoPeerRejected); ok {
		return x.ErrInfoPeerRejected
	}
	return nil
}

func (x *MsgError) GetErrInfoPeerNotFunded() *ErrInfoPeerNotFunded {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoPeerNotFunded); ok {
		return x.ErrInfoPeerNotFunded
	}
	return nil
}

func (x *MsgError) GetErrInfoUserResponseTimedOut() *ErrInfoUserResponseTimedOut {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoUserResponseTimedOut); ok {
		return x.ErrInfoUserResponseTimedOut
	}
	return nil
}

func (x *MsgError) GetErrInfoResourceNotFound() *ErrInfoResourceNotFound {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoResourceNotFound); ok {
		return x.ErrInfoResourceNotFound
	}
	return nil
}

func (x *MsgError) GetErrInfoResourceExists() *ErrInfoResourceExists {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoResourceExists); ok {
		return x.ErrInfoResourceExists
	}
	return nil
}

func (x *MsgError) GetErrInfoInvalidArgument() *ErrInfoInvalidArgument {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoInvalidArgument); ok {
		return x.ErrInfoInvalidArgument
	}
	return nil
}

func (x *MsgError) GetErrInfoFailedPreCondUnclosedChs() *ErrInfoFailedPreCondUnclosedChs {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoFailedPreCondUnclosedChs); ok {
		return x.ErrInfoFailedPreCondUnclosedChs
	}
	return nil
}

func (x *MsgError) GetErrInfoInvalidConfig() *ErrInfoInvalidConfig {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoInvalidConfig); ok {
		return x.ErrInfoInvalidConfig
	}
	return nil
}

func (x *MsgError) GetErrInfoInvalidContracts() *ErrInfoInvalidContracts {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoInvalidContracts); ok {
		return x.ErrInfoInvalidContracts
	}
	return nil
}

func (x *MsgError) GetErrInfoTxTimedOut() *ErrInfoTxTimedOut {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoTxTimedOut); ok {
		return x.ErrInfoTxTimedOut
	}
	return nil
}

func (x *MsgError) GetErrInfoChainNotReachable() *ErrInfoChainNotReachable {
	if x, ok := x.GetAddInfo().(*MsgError_ErrInfoChainNotReachable); ok {
		return x.ErrInfoChainNotReachable
	}
	return nil
}

type isMsgError_AddInfo interface {
	isMsgError_AddInfo()
}

type MsgError_ErrInfoPeerRequestTimedOut struct {
	ErrInfoPeerRequestTimedOut *ErrInfoPeerRequestTimedOut `protobuf:"bytes,4,opt,name=ErrInfoPeerRequestTimedOut,proto3,oneof"`
}

type MsgError_ErrInfoPeerRejected struct {
	ErrInfoPeerRejected *ErrInfoPeerRejected `protobuf:"bytes,5,opt,name=ErrInfoPeerRejected,proto3,oneof"`
}

type MsgError_ErrInfoPeerNotFunded struct {
	ErrInfoPeerNotFunded *ErrInfoPeerNotFunded `protobuf:"bytes,6,opt,name=ErrInfoPeerNotFunded,proto3,oneof"`
}

type MsgError_ErrInfoUserResponseTimedOut struct {
	ErrInfoUserResponseTimedOut *ErrInfoUserResponseTimedOut `protobuf:"bytes,7,opt,name=ErrInfoUserResponseTimedOut,proto3,oneof"`
}

type MsgError_ErrInfoResourceNotFound struct {
	ErrInfoResourceNotFound *ErrInfoResourceNotFound `protobuf:"bytes,8,opt,name=ErrInfoResourceNotFound,proto3,oneof"`
}

type MsgError_ErrInfoResourceExists struct {
	ErrInfoResourceExists *ErrInfoResourceExists `protobuf:"bytes,9,opt,name=ErrInfoResourceExists,proto3,oneof"`
}

type MsgError_ErrInfoInvalidArgument struct {
	ErrInfoInvalidArgument *ErrInfoInvalidArgument `protobuf:"bytes,10,opt,name=ErrInfoInvalidArgument,proto3,oneof"`
}

type MsgError_ErrInfoFailedPreCondUnclosedChs struct {
	ErrInfoFailedPreCondUnclosedChs *ErrInfoFailedPreCondUnclosedChs `protobuf:"bytes,11,opt,name=ErrInfoFailedPreCondUnclosedChs,proto3,oneof"`
}

type MsgError_ErrInfoInvalidConfig struct {
	ErrInfoInvalidConfig *ErrInfoInvalidConfig `protobuf:"bytes,13,opt,name=ErrInfoInvalidConfig,proto3,oneof"`
}

type MsgError_ErrInfoInvalidContracts struct {
	ErrInfoInvalidContracts *ErrInfoInvalidContracts `protobuf:"bytes,14,opt,name=ErrInfoInvalidContracts,proto3,oneof"`
}

type MsgError_ErrInfoTxTimedOut struct {
	ErrInfoTxTimedOut *ErrInfoTxTimedOut `protobuf:"bytes,15,opt,name=ErrInfoTxTimedOut,proto3,oneof"`
}

type MsgError_ErrInfoChainNotReachable struct {
	ErrInfoChainNotReachable *ErrInfoChainNotReachable `protobuf:"bytes,16,opt,name=ErrInfoChainNotReachable,proto3,oneof"`
}

func (*MsgError_ErrInfoPeerRequestTimedOut) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoPeerRejected) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoPeerNotFunded) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoUserResponseTimedOut) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoResourceNotFound) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoResourceExists) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoInvalidArgument) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoFailedPreCondUnclosedChs) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoInvalidConfig) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoInvalidContracts) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoTxTimedOut) isMsgError_AddInfo() {}

func (*MsgError_ErrInfoChainNotReachable) isMsgError_AddInfo() {}

type ErrInfoPeerRequestTimedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerAlias string `protobuf:"bytes,1,opt,name=peerAlias,proto3" json:"peerAlias,omitempty"`
	Timeout   string `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *ErrInfoPeerRequestTimedOut) Reset() {
	*x = ErrInfoPeerRequestTimedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoPeerRequestTimedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoPeerRequestTimedOut) ProtoMessage() {}

func (x *ErrInfoPeerRequestTimedOut) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoPeerRequestTimedOut.ProtoReflect.Descriptor instead.
func (*ErrInfoPeerRequestTimedOut) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrInfoPeerRequestTimedOut) GetPeerAlias() string {
	if x != nil {
		return x.PeerAlias
	}
	return ""
}

func (x *ErrInfoPeerRequestTimedOut) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type ErrInfoPeerRejected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerAlias string `protobuf:"bytes,1,opt,name=peerAlias,proto3" json:"peerAlias,omitempty"`
	Reason    string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ErrInfoPeerRejected) Reset() {
	*x = ErrInfoPeerRejected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoPeerRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoPeerRejected) ProtoMessage() {}

func (x *ErrInfoPeerRejected) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoPeerRejected.ProtoReflect.Descriptor instead.
func (*ErrInfoPeerRejected) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ErrInfoPeerRejected) GetPeerAlias() string {
	if x != nil {
		return x.PeerAlias
	}
	return ""
}

func (x *ErrInfoPeerRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ErrInfoPeerNotFunded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerAlias string `protobuf:"bytes,1,opt,name=peerAlias,proto3" json:"peerAlias,omitempty"`
}

func (x *ErrInfoPeerNotFunded) Reset() {
	*x = ErrInfoPeerNotFunded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoPeerNotFunded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoPeerNotFunded) ProtoMessage() {}

func (x *ErrInfoPeerNotFunded) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoPeerNotFunded.ProtoReflect.Descriptor instead.
func (*ErrInfoPeerNotFunded) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{3}
}

func (x *ErrInfoPeerNotFunded) GetPeerAlias() string {
	if x != nil {
		return x.PeerAlias
	}
	return ""
}

type ErrInfoUserResponseTimedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expiry     int64 `protobuf:"varint,1,opt,name=expiry,proto3" json:"expiry,omitempty"`
	ReceivedAt int64 `protobuf:"varint,2,opt,name=receivedAt,proto3" json:"receivedAt,omitempty"`
}

func (x *ErrInfoUserResponseTimedOut) Reset() {
	*x = ErrInfoUserResponseTimedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoUserResponseTimedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoUserResponseTimedOut) ProtoMessage() {}

func (x *ErrInfoUserResponseTimedOut) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoUserResponseTimedOut.ProtoReflect.Descriptor instead.
func (*ErrInfoUserResponseTimedOut) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{4}
}

func (x *ErrInfoUserResponseTimedOut) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *ErrInfoUserResponseTimedOut) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type ErrInfoResourceNotFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ErrInfoResourceNotFound) Reset() {
	*x = ErrInfoResourceNotFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoResourceNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoResourceNotFound) ProtoMessage() {}

func (x *ErrInfoResourceNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoResourceNotFound.ProtoReflect.Descriptor instead.
func (*ErrInfoResourceNotFound) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{5}
}

func (x *ErrInfoResourceNotFound) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrInfoResourceNotFound) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ErrInfoResourceExists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ErrInfoResourceExists) Reset() {
	*x = ErrInfoResourceExists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoResourceExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoResourceExists) ProtoMessage() {}

func (x *ErrInfoResourceExists) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoResourceExists.ProtoReflect.Descriptor instead.
func (*ErrInfoResourceExists) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{6}
}

func (x *ErrInfoResourceExists) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrInfoResourceExists) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ErrInfoInvalidArgument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value       string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Requirement string `protobuf:"bytes,3,opt,name=requirement,proto3" json:"requirement,omitempty"`
}

func (x *ErrInfoInvalidArgument) Reset() {
	*x = ErrInfoInvalidArgument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoInvalidArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoInvalidArgument) ProtoMessage() {}

func (x *ErrInfoInvalidArgument) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoInvalidArgument.ProtoReflect.Descriptor instead.
func (*ErrInfoInvalidArgument) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{7}
}

func (x *ErrInfoInvalidArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ErrInfoInvalidArgument) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ErrInfoInvalidArgument) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

type ErrInfoFailedPreCondUnclosedChs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chs []*PayChInfo `protobuf:"bytes,1,rep,name=chs,proto3" json:"chs,omitempty"`
}

func (x *ErrInfoFailedPreCondUnclosedChs) Reset() {
	*x = ErrInfoFailedPreCondUnclosedChs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoFailedPreCondUnclosedChs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoFailedPreCondUnclosedChs) ProtoMessage() {}

func (x *ErrInfoFailedPreCondUnclosedChs) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoFailedPreCondUnclosedChs.ProtoReflect.Descriptor instead.
func (*ErrInfoFailedPreCondUnclosedChs) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{8}
}

func (x *ErrInfoFailedPreCondUnclosedChs) GetChs() []*PayChInfo {
	if x != nil {
		return x.Chs
	}
	return nil
}

type ErrInfoInvalidConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ErrInfoInvalidConfig) Reset() {
	*x = ErrInfoInvalidConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoInvalidConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoInvalidConfig) ProtoMessage() {}

func (x *ErrInfoInvalidConfig) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoInvalidConfig.ProtoReflect.Descriptor instead.
func (*ErrInfoInvalidConfig) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{9}
}

func (x *ErrInfoInvalidConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ErrInfoInvalidConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ContractErrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ContractErrInfo) Reset() {
	*x = ContractErrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractErrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractErrInfo) ProtoMessage() {}

func (x *ContractErrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractErrInfo.ProtoReflect.Descriptor instead.
func (*ContractErrInfo) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{10}
}

func (x *ContractErrInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractErrInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContractErrInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ErrInfoInvalidContracts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractErrInfos []*ContractErrInfo `protobuf:"bytes,1,rep,name=ContractErrInfos,proto3" json:"ContractErrInfos,omitempty"`
}

func (x *ErrInfoInvalidContracts) Reset() {
	*x = ErrInfoInvalidContracts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoInvalidContracts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoInvalidContracts) ProtoMessage() {}

func (x *ErrInfoInvalidContracts) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoInvalidContracts.ProtoReflect.Descriptor instead.
func (*ErrInfoInvalidContracts) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{11}
}

func (x *ErrInfoInvalidContracts) GetContractErrInfos() []*ContractErrInfo {
	if x != nil {
		return x.ContractErrInfos
	}
	return nil
}

type ErrInfoTxTimedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxType    string `protobuf:"bytes,1,opt,name=txType,proto3" json:"txType,omitempty"`
	TxID      string `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
	TxTimeout string `protobuf:"bytes,3,opt,name=txTimeout,proto3" json:"txTimeout,omitempty"`
}

func (x *ErrInfoTxTimedOut) Reset() {
	*x = ErrInfoTxTimedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoTxTimedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoTxTimedOut) ProtoMessage() {}

func (x *ErrInfoTxTimedOut) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoTxTimedOut.ProtoReflect.Descriptor instead.
func (*ErrInfoTxTimedOut) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{12}
}

func (x *ErrInfoTxTimedOut) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

func (x *ErrInfoTxTimedOut) GetTxID() string {
	if x != nil {
		return x.TxID
	}
	return ""
}

func (x *ErrInfoTxTimedOut) GetTxTimeout() string {
	if x != nil {
		return x.TxTimeout
	}
	return ""
}

type ErrInfoChainNotReachable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainURL string `protobuf:"bytes,1,opt,name=chainURL,proto3" json:"chainURL,omitempty"`
}

func (x *ErrInfoChainNotReachable) Reset() {
	*x = ErrInfoChainNotReachable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrInfoChainNotReachable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrInfoChainNotReachable) ProtoMessage() {}

func (x *ErrInfoChainNotReachable) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrInfoChainNotReachable.ProtoReflect.Descriptor instead.
func (*ErrInfoChainNotReachable) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{13}
}

func (x *ErrInfoChainNotReachable) GetChainURL() string {
	if x != nil {
		return x.ChainURL
	}
	return ""
}

var File_errors_proto protoreflect.FileDescriptor

var file_errors_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x09, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x2d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x21, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x60, 0x0a, 0x1a,
	0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74,
	0x48, 0x00, 0x52, 0x1a, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x4b,
	0x0a, 0x13, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x13, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x4e, 0x0a, 0x14, 0x45,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x75, 0x6e,
	0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x75, 0x6e,
	0x64, 0x65, 0x64, 0x48, 0x00, 0x52, 0x14, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65,
	0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x75, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x63, 0x0a, 0x1b, 0x45,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75,
	0x74, 0x48, 0x00, 0x52, 0x1b, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74,
	0x12, 0x57, 0x0a, 0x17, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x48, 0x00,
	0x52, 0x17, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x51, 0x0a, 0x15, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x48, 0x00, 0x52, 0x15, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x54, 0x0a, 0x16,
	0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x16, 0x45, 0x72, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x6f, 0x0a, 0x1f, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x50, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x55, 0x6e, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x64, 0x43, 0x68, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x50, 0x72,
	0x65, 0x43, 0x6f, 0x6e, 0x64, 0x55, 0x6e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x43, 0x68, 0x73,
	0x48, 0x00, 0x52, 0x1f, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x50, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x55, 0x6e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x43, 0x68, 0x73, 0x12, 0x4e, 0x0a, 0x14, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x14, 0x45,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x57, 0x0a, 0x17, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x17, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x12, 0x45, 0x0a, 0x11,
	0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75,
	0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x48, 0x00,
	0x52, 0x11, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x64,
	0x4f, 0x75, 0x74, 0x12, 0x5a, 0x0a, 0x18, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61,
	0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x18, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x54, 0x0a, 0x1a, 0x45, 0x72,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x65,
	0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x22, 0x4b, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x65, 0x72,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x34, 0x0a,
	0x14, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46,
	0x75, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x65, 0x72, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x65, 0x72, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x22, 0x55, 0x0a, 0x1b, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x3d, 0x0a, 0x17, 0x45, 0x72,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74,
	0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x15, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x16, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x42, 0x0a, 0x1f,
	0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x50, 0x72, 0x65,
	0x43, 0x6f, 0x6e, 0x64, 0x55, 0x6e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x43, 0x68, 0x73, 0x12,
	0x1f, 0x0a, 0x03, 0x63, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x79, 0x43, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x63, 0x68, 0x73,
	0x22, 0x40, 0x0a, 0x14, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x55, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x72,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5a, 0x0a, 0x17, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x72, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x5d, 0x0a, 0x11, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x78, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x78, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x78, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x22, 0x36, 0x0a, 0x18, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x2a, 0x5c, 0x0a, 0x0d,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a,
	0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x03, 0x2a, 0xe7, 0x02, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x00,
	0x12, 0x1a, 0x0a, 0x16, 0x45, 0x72, 0x72, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x10, 0x65, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x72, 0x72, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10,
	0x66, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46,
	0x75, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x67, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x72, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x10, 0x68, 0x12, 0x18, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0xc9, 0x01, 0x12, 0x16,
	0x0a, 0x11, 0x45, 0x72, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x10, 0xca, 0x01, 0x12, 0x17, 0x0a, 0x12, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0xcb, 0x01, 0x12,
	0x1a, 0x0a, 0x15, 0x45, 0x72, 0x72, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x50, 0x72, 0x65, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0xcc, 0x01, 0x12, 0x15, 0x0a, 0x10, 0x45,
	0x72, 0x72, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x10,
	0xcd, 0x01, 0x12, 0x18, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x10, 0xce, 0x01, 0x12, 0x12, 0x0a, 0x0d,
	0x45, 0x72, 0x72, 0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x10, 0xad, 0x02,
	0x12, 0x19, 0x0a, 0x14, 0x45, 0x72, 0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x10, 0xae, 0x02, 0x12, 0x17, 0x0a, 0x12, 0x45,
	0x72, 0x72, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x10, 0x91, 0x03, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData = file_errors_proto_rawDesc
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_errors_proto_rawDescData)
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_errors_proto_goTypes = []interface{}{
	(ErrorCategory)(0),                      // 0: pb.ErrorCategory
	(ErrorCode)(0),                          // 1: pb.ErrorCode
	(*MsgError)(nil),                        // 2: pb.MsgError
	(*ErrInfoPeerRequestTimedOut)(nil),      // 3: pb.ErrInfoPeerRequestTimedOut
	(*ErrInfoPeerRejected)(nil),             // 4: pb.ErrInfoPeerRejected
	(*ErrInfoPeerNotFunded)(nil),            // 5: pb.ErrInfoPeerNotFunded
	(*ErrInfoUserResponseTimedOut)(nil),     // 6: pb.ErrInfoUserResponseTimedOut
	(*ErrInfoResourceNotFound)(nil),         // 7: pb.ErrInfoResourceNotFound
	(*ErrInfoResourceExists)(nil),           // 8: pb.ErrInfoResourceExists
	(*ErrInfoInvalidArgument)(nil),          // 9: pb.ErrInfoInvalidArgument
	(*ErrInfoFailedPreCondUnclosedChs)(nil), // 10: pb.ErrInfoFailedPreCondUnclosedChs
	(*ErrInfoInvalidConfig)(nil),            // 11: pb.ErrInfoInvalidConfig
	(*ContractErrInfo)(nil),                 // 12: pb.ContractErrInfo
	(*ErrInfoInvalidContracts)(nil),         // 13: pb.ErrInfoInvalidContracts
	(*ErrInfoTxTimedOut)(nil),               // 14: pb.ErrInfoTxTimedOut
	(*ErrInfoChainNotReachable)(nil),        // 15: pb.ErrInfoChainNotReachable
	(*PayChInfo)(nil),                       // 16: pb.PayChInfo
}
var file_errors_proto_depIdxs = []int32{
	0,  // 0: pb.MsgError.category:type_name -> pb.ErrorCategory
	1,  // 1: pb.MsgError.code:type_name -> pb.ErrorCode
	3,  // 2: pb.MsgError.ErrInfoPeerRequestTimedOut:type_name -> pb.ErrInfoPeerRequestTimedOut
	4,  // 3: pb.MsgError.ErrInfoPeerRejected:type_name -> pb.ErrInfoPeerRejected
	5,  // 4: pb.MsgError.ErrInfoPeerNotFunded:type_name -> pb.ErrInfoPeerNotFunded
	6,  // 5: pb.MsgError.ErrInfoUserResponseTimedOut:type_name -> pb.ErrInfoUserResponseTimedOut
	7,  // 6: pb.MsgError.ErrInfoResourceNotFound:type_name -> pb.ErrInfoResourceNotFound
	8,  // 7: pb.MsgError.ErrInfoResourceExists:type_name -> pb.ErrInfoResourceExists
	9,  // 8: pb.MsgError.ErrInfoInvalidArgument:type_name -> pb.ErrInfoInvalidArgument
	10, // 9: pb.MsgError.ErrInfoFailedPreCondUnclosedChs:type_name -> pb.ErrInfoFailedPreCondUnclosedChs
	11, // 10: pb.MsgError.ErrInfoInvalidConfig:type_name -> pb.ErrInfoInvalidConfig
	13, // 11: pb.MsgError.ErrInfoInvalidContracts:type_name -> pb.ErrInfoInvalidContracts
	14, // 12: pb.MsgError.ErrInfoTxTimedOut:type_name -> pb.ErrInfoTxTimedOut
	15, // 13: pb.MsgError.ErrInfoChainNotReachable:type_name -> pb.ErrInfoChainNotReachable
	16, // 14: pb.ErrInfoFailedPreCondUnclosedChs.chs:type_name -> pb.PayChInfo
	12, // 15: pb.ErrInfoInvalidContracts.ContractErrInfos:type_name -> pb.ContractErrInfo
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	file_nodetypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_errors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoPeerRequestTimedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoPeerRejected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoPeerNotFunded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoUserResponseTimedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoResourceNotFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoResourceExists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoInvalidArgument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoFailedPreCondUnclosedChs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoInvalidConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractErrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoInvalidContracts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoTxTimedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_errors_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrInfoChainNotReachable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_errors_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MsgError_ErrInfoPeerRequestTimedOut)(nil),
		(*MsgError_ErrInfoPeerRejected)(nil),
		(*MsgError_ErrInfoPeerNotFunded)(nil),
		(*MsgError_ErrInfoUserResponseTimedOut)(nil),
		(*MsgError_ErrInfoResourceNotFound)(nil),
		(*MsgError_ErrInfoResourceExists)(nil),
		(*MsgError_ErrInfoInvalidArgument)(nil),
		(*MsgError_ErrInfoFailedPreCondUnclosedChs)(nil),
		(*MsgError_ErrInfoInvalidConfig)(nil),
		(*MsgError_ErrInfoInvalidContracts)(nil),
		(*MsgError_ErrInfoTxTimedOut)(nil),
		(*MsgError_ErrInfoChainNotReachable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errors_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_rawDesc = nil
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
