// Copyright (c) 2023 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/hyperledger-labs/perun-node
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: sdktypes.proto

// Package pb contains proto3 definitions for user API and the corresponding
// generated code for grpc server and client.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdjudicatorEventBase_TimeoutType int32

const (
	AdjudicatorEventBase_elapsed  AdjudicatorEventBase_TimeoutType = 0
	AdjudicatorEventBase_time     AdjudicatorEventBase_TimeoutType = 1
	AdjudicatorEventBase_ethBlock AdjudicatorEventBase_TimeoutType = 2
)

// Enum value maps for AdjudicatorEventBase_TimeoutType.
var (
	AdjudicatorEventBase_TimeoutType_name = map[int32]string{
		0: "elapsed",
		1: "time",
		2: "ethBlock",
	}
	AdjudicatorEventBase_TimeoutType_value = map[string]int32{
		"elapsed":  0,
		"time":     1,
		"ethBlock": 2,
	}
)

func (x AdjudicatorEventBase_TimeoutType) Enum() *AdjudicatorEventBase_TimeoutType {
	p := new(AdjudicatorEventBase_TimeoutType)
	*p = x
	return p
}

func (x AdjudicatorEventBase_TimeoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdjudicatorEventBase_TimeoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdktypes_proto_enumTypes[0].Descriptor()
}

func (AdjudicatorEventBase_TimeoutType) Type() protoreflect.EnumType {
	return &file_sdktypes_proto_enumTypes[0]
}

func (x AdjudicatorEventBase_TimeoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdjudicatorEventBase_TimeoutType.Descriptor instead.
func (AdjudicatorEventBase_TimeoutType) EnumDescriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{8, 0}
}

// Balance represents the balance of a single asset, for all the channel
// participants.
type Balance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance [][]byte `protobuf:"bytes,1,rep,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Balance) Reset() {
	*x = Balance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetBalance() [][]byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

// Balances represents the balance of all the assets, for all the channel
// participants.
type Balances struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balances []*Balance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
}

func (x *Balances) Reset() {
	*x = Balances{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Balances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balances) ProtoMessage() {}

func (x *Balances) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balances.ProtoReflect.Descriptor instead.
func (*Balances) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{1}
}

func (x *Balances) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

// Params represents channel.Params.
type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChallengeDuration uint64   `protobuf:"varint,2,opt,name=challenge_duration,json=challengeDuration,proto3" json:"challenge_duration,omitempty"`
	Parts             [][]byte `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	App               []byte   `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	Nonce             []byte   `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	LedgerChannel     bool     `protobuf:"varint,6,opt,name=ledger_channel,json=ledgerChannel,proto3" json:"ledger_channel,omitempty"`
	VirtualChannel    bool     `protobuf:"varint,7,opt,name=virtual_channel,json=virtualChannel,proto3" json:"virtual_channel,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{2}
}

func (x *Params) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Params) GetChallengeDuration() uint64 {
	if x != nil {
		return x.ChallengeDuration
	}
	return 0
}

func (x *Params) GetParts() [][]byte {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Params) GetApp() []byte {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Params) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Params) GetLedgerChannel() bool {
	if x != nil {
		return x.LedgerChannel
	}
	return false
}

func (x *Params) GetVirtualChannel() bool {
	if x != nil {
		return x.VirtualChannel
	}
	return false
}

// IndexMap represents the mapping of a participant indices in a sub allocation
// or a virtual channel funding proposal to the corresponding indices in the
// parent channel.
type IndexMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexMap []uint32 `protobuf:"varint,1,rep,packed,name=index_map,json=indexMap,proto3" json:"index_map,omitempty"`
}

func (x *IndexMap) Reset() {
	*x = IndexMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMap) ProtoMessage() {}

func (x *IndexMap) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMap.ProtoReflect.Descriptor instead.
func (*IndexMap) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{3}
}

func (x *IndexMap) GetIndexMap() []uint32 {
	if x != nil {
		return x.IndexMap
	}
	return nil
}

// SubAlloc represts a sub allocation.
type SubAlloc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       []byte    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bals     *Balance  `protobuf:"bytes,2,opt,name=bals,proto3" json:"bals,omitempty"`
	IndexMap *IndexMap `protobuf:"bytes,3,opt,name=index_map,json=indexMap,proto3" json:"index_map,omitempty"`
}

func (x *SubAlloc) Reset() {
	*x = SubAlloc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAlloc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAlloc) ProtoMessage() {}

func (x *SubAlloc) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAlloc.ProtoReflect.Descriptor instead.
func (*SubAlloc) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{4}
}

func (x *SubAlloc) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SubAlloc) GetBals() *Balance {
	if x != nil {
		return x.Bals
	}
	return nil
}

func (x *SubAlloc) GetIndexMap() *IndexMap {
	if x != nil {
		return x.IndexMap
	}
	return nil
}

// Allocation represents channel.Allocation.
type Allocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets   [][]byte    `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Balances *Balances   `protobuf:"bytes,2,opt,name=balances,proto3" json:"balances,omitempty"`
	Locked   []*SubAlloc `protobuf:"bytes,3,rep,name=locked,proto3" json:"locked,omitempty"`
}

func (x *Allocation) Reset() {
	*x = Allocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Allocation) ProtoMessage() {}

func (x *Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Allocation.ProtoReflect.Descriptor instead.
func (*Allocation) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{5}
}

func (x *Allocation) GetAssets() [][]byte {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *Allocation) GetBalances() *Balances {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *Allocation) GetLocked() []*SubAlloc {
	if x != nil {
		return x.Locked
	}
	return nil
}

// State represents channel.State.
type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         []byte      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version    uint64      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	App        []byte      `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Allocation *Allocation `protobuf:"bytes,4,opt,name=allocation,proto3" json:"allocation,omitempty"`
	Data       []byte      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	IsFinal    bool        `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{6}
}

func (x *State) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *State) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *State) GetApp() []byte {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *State) GetAllocation() *Allocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

func (x *State) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *State) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// AdjudicatorReq represents channel.AdjudicatorReq.
type AdjudicatorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params    *Params      `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Acc       []byte       `protobuf:"bytes,2,opt,name=acc,proto3" json:"acc,omitempty"`
	Tx        *Transaction `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	Idx       uint32       `protobuf:"varint,4,opt,name=idx,proto3" json:"idx,omitempty"`
	Secondary bool         `protobuf:"varint,5,opt,name=secondary,proto3" json:"secondary,omitempty"`
}

func (x *AdjudicatorReq) Reset() {
	*x = AdjudicatorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjudicatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjudicatorReq) ProtoMessage() {}

func (x *AdjudicatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjudicatorReq.ProtoReflect.Descriptor instead.
func (*AdjudicatorReq) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{7}
}

func (x *AdjudicatorReq) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AdjudicatorReq) GetAcc() []byte {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *AdjudicatorReq) GetTx() *Transaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *AdjudicatorReq) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *AdjudicatorReq) GetSecondary() bool {
	if x != nil {
		return x.Secondary
	}
	return false
}

// AdjudicatorEventBase represents channel.AdjudicatorEventBase.
type AdjudicatorEventBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChID    []byte                        `protobuf:"bytes,1,opt,name=chID,proto3" json:"chID,omitempty"`
	Timeout *AdjudicatorEventBase_Timeout `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Version uint64                        `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AdjudicatorEventBase) Reset() {
	*x = AdjudicatorEventBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjudicatorEventBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjudicatorEventBase) ProtoMessage() {}

func (x *AdjudicatorEventBase) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjudicatorEventBase.ProtoReflect.Descriptor instead.
func (*AdjudicatorEventBase) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{8}
}

func (x *AdjudicatorEventBase) GetChID() []byte {
	if x != nil {
		return x.ChID
	}
	return nil
}

func (x *AdjudicatorEventBase) GetTimeout() *AdjudicatorEventBase_Timeout {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *AdjudicatorEventBase) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// RegisteredEvent represents channel.RegisteredEvent.
type RegisteredEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdjudicatorEventBase *AdjudicatorEventBase `protobuf:"bytes,1,opt,name=adjudicatorEventBase,proto3" json:"adjudicatorEventBase,omitempty"`
	State                *State                `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Sigs                 [][]byte              `protobuf:"bytes,3,rep,name=sigs,proto3" json:"sigs,omitempty"`
}

func (x *RegisteredEvent) Reset() {
	*x = RegisteredEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredEvent) ProtoMessage() {}

func (x *RegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredEvent.ProtoReflect.Descriptor instead.
func (*RegisteredEvent) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{9}
}

func (x *RegisteredEvent) GetAdjudicatorEventBase() *AdjudicatorEventBase {
	if x != nil {
		return x.AdjudicatorEventBase
	}
	return nil
}

func (x *RegisteredEvent) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RegisteredEvent) GetSigs() [][]byte {
	if x != nil {
		return x.Sigs
	}
	return nil
}

// ProgressedEvent represents channel.ProgressedEvent.
type ProgressedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdjudicatorEventBase *AdjudicatorEventBase `protobuf:"bytes,1,opt,name=adjudicatorEventBase,proto3" json:"adjudicatorEventBase,omitempty"`
	State                *State                `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Idx                  uint32                `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *ProgressedEvent) Reset() {
	*x = ProgressedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgressedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressedEvent) ProtoMessage() {}

func (x *ProgressedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressedEvent.ProtoReflect.Descriptor instead.
func (*ProgressedEvent) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{10}
}

func (x *ProgressedEvent) GetAdjudicatorEventBase() *AdjudicatorEventBase {
	if x != nil {
		return x.AdjudicatorEventBase
	}
	return nil
}

func (x *ProgressedEvent) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ProgressedEvent) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

// ConcludedEvent represents channel.ConcludedEvent.
type ConcludedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdjudicatorEventBase *AdjudicatorEventBase `protobuf:"bytes,1,opt,name=adjudicatorEventBase,proto3" json:"adjudicatorEventBase,omitempty"`
}

func (x *ConcludedEvent) Reset() {
	*x = ConcludedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConcludedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcludedEvent) ProtoMessage() {}

func (x *ConcludedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcludedEvent.ProtoReflect.Descriptor instead.
func (*ConcludedEvent) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{11}
}

func (x *ConcludedEvent) GetAdjudicatorEventBase() *AdjudicatorEventBase {
	if x != nil {
		return x.AdjudicatorEventBase
	}
	return nil
}

// Transaction represents channel.Transaction.
type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Sigs  [][]byte `protobuf:"bytes,2,rep,name=sigs,proto3" json:"sigs,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{12}
}

func (x *Transaction) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Transaction) GetSigs() [][]byte {
	if x != nil {
		return x.Sigs
	}
	return nil
}

// SignedState represents channel.SignedState.
type SignedState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *Params  `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	State  *State   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Sigs   [][]byte `protobuf:"bytes,3,rep,name=sigs,proto3" json:"sigs,omitempty"`
}

func (x *SignedState) Reset() {
	*x = SignedState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedState) ProtoMessage() {}

func (x *SignedState) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedState.ProtoReflect.Descriptor instead.
func (*SignedState) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{13}
}

func (x *SignedState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *SignedState) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SignedState) GetSigs() [][]byte {
	if x != nil {
		return x.Sigs
	}
	return nil
}

// StateMap represents channel.StateMap.
type StateMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State *State `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *StateMap) Reset() {
	*x = StateMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateMap) ProtoMessage() {}

func (x *StateMap) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateMap.ProtoReflect.Descriptor instead.
func (*StateMap) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{14}
}

func (x *StateMap) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *StateMap) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

type AdjudicatorEventBase_Timeout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sec  int64                            `protobuf:"varint,1,opt,name=sec,proto3" json:"sec,omitempty"`
	Type AdjudicatorEventBase_TimeoutType `protobuf:"varint,3,opt,name=type,proto3,enum=pb.AdjudicatorEventBase_TimeoutType" json:"type,omitempty"`
}

func (x *AdjudicatorEventBase_Timeout) Reset() {
	*x = AdjudicatorEventBase_Timeout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdktypes_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjudicatorEventBase_Timeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjudicatorEventBase_Timeout) ProtoMessage() {}

func (x *AdjudicatorEventBase_Timeout) ProtoReflect() protoreflect.Message {
	mi := &file_sdktypes_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjudicatorEventBase_Timeout.ProtoReflect.Descriptor instead.
func (*AdjudicatorEventBase_Timeout) Descriptor() ([]byte, []int) {
	return file_sdktypes_proto_rawDescGZIP(), []int{8, 0}
}

func (x *AdjudicatorEventBase_Timeout) GetSec() int64 {
	if x != nil {
		return x.Sec
	}
	return 0
}

func (x *AdjudicatorEventBase_Timeout) GetType() AdjudicatorEventBase_TimeoutType {
	if x != nil {
		return x.Type
	}
	return AdjudicatorEventBase_elapsed
}

var File_sdktypes_proto protoreflect.FileDescriptor

var file_sdktypes_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x64, 0x6b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x23, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x33, 0x0a, 0x08, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xd5,
	0x01, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x70, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x27, 0x0a,
	0x0f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x27, 0x0a, 0x08, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d,
	0x61, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x61, 0x70, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x61, 0x70, 0x22,
	0x66, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x62,
	0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x04, 0x62, 0x61, 0x6c, 0x73, 0x12, 0x29, 0x0a, 0x09,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4d, 0x61, 0x70, 0x52, 0x08, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x4d, 0x61, 0x70, 0x22, 0x74, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x28, 0x0a,
	0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x08, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62,
	0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22, 0xa2, 0x01,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x61, 0x70, 0x70, 0x12, 0x2e, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61, 0x63, 0x63, 0x12, 0x1f, 0x0a, 0x02, 0x74,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x78, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x22, 0x8b, 0x02, 0x0a,
	0x14, 0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x42, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x68, 0x49, 0x44, 0x12, 0x3a, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x42, 0x61, 0x73, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a,
	0x55, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x63, 0x12, 0x38, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x42, 0x61, 0x73, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x65, 0x74, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x02, 0x22, 0x94, 0x01, 0x0a, 0x0f, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4c,
	0x0a, 0x14, 0x61, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x14, 0x61, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x73, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4c, 0x0a, 0x14, 0x61, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x52, 0x14, 0x61,
	0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42,
	0x61, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x69, 0x64, 0x78, 0x22, 0x5e, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4c, 0x0a, 0x14, 0x61, 0x64, 0x6a, 0x75,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x6a, 0x75,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x14, 0x61, 0x64, 0x6a, 0x75, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x73, 0x22, 0x66, 0x0a, 0x0b, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69,
	0x67, 0x73, 0x22, 0x3b, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdktypes_proto_rawDescOnce sync.Once
	file_sdktypes_proto_rawDescData = file_sdktypes_proto_rawDesc
)

func file_sdktypes_proto_rawDescGZIP() []byte {
	file_sdktypes_proto_rawDescOnce.Do(func() {
		file_sdktypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdktypes_proto_rawDescData)
	})
	return file_sdktypes_proto_rawDescData
}

var file_sdktypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdktypes_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_sdktypes_proto_goTypes = []interface{}{
	(AdjudicatorEventBase_TimeoutType)(0), // 0: pb.AdjudicatorEventBase.TimeoutType
	(*Balance)(nil),                       // 1: pb.Balance
	(*Balances)(nil),                      // 2: pb.Balances
	(*Params)(nil),                        // 3: pb.Params
	(*IndexMap)(nil),                      // 4: pb.IndexMap
	(*SubAlloc)(nil),                      // 5: pb.SubAlloc
	(*Allocation)(nil),                    // 6: pb.Allocation
	(*State)(nil),                         // 7: pb.State
	(*AdjudicatorReq)(nil),                // 8: pb.AdjudicatorReq
	(*AdjudicatorEventBase)(nil),          // 9: pb.AdjudicatorEventBase
	(*RegisteredEvent)(nil),               // 10: pb.RegisteredEvent
	(*ProgressedEvent)(nil),               // 11: pb.ProgressedEvent
	(*ConcludedEvent)(nil),                // 12: pb.ConcludedEvent
	(*Transaction)(nil),                   // 13: pb.Transaction
	(*SignedState)(nil),                   // 14: pb.SignedState
	(*StateMap)(nil),                      // 15: pb.StateMap
	(*AdjudicatorEventBase_Timeout)(nil),  // 16: pb.AdjudicatorEventBase.Timeout
}
var file_sdktypes_proto_depIdxs = []int32{
	1,  // 0: pb.Balances.balances:type_name -> pb.Balance
	1,  // 1: pb.SubAlloc.bals:type_name -> pb.Balance
	4,  // 2: pb.SubAlloc.index_map:type_name -> pb.IndexMap
	2,  // 3: pb.Allocation.balances:type_name -> pb.Balances
	5,  // 4: pb.Allocation.locked:type_name -> pb.SubAlloc
	6,  // 5: pb.State.allocation:type_name -> pb.Allocation
	3,  // 6: pb.AdjudicatorReq.params:type_name -> pb.Params
	13, // 7: pb.AdjudicatorReq.tx:type_name -> pb.Transaction
	16, // 8: pb.AdjudicatorEventBase.timeout:type_name -> pb.AdjudicatorEventBase.Timeout
	9,  // 9: pb.RegisteredEvent.adjudicatorEventBase:type_name -> pb.AdjudicatorEventBase
	7,  // 10: pb.RegisteredEvent.state:type_name -> pb.State
	9,  // 11: pb.ProgressedEvent.adjudicatorEventBase:type_name -> pb.AdjudicatorEventBase
	7,  // 12: pb.ProgressedEvent.state:type_name -> pb.State
	9,  // 13: pb.ConcludedEvent.adjudicatorEventBase:type_name -> pb.AdjudicatorEventBase
	7,  // 14: pb.Transaction.state:type_name -> pb.State
	3,  // 15: pb.SignedState.params:type_name -> pb.Params
	7,  // 16: pb.SignedState.state:type_name -> pb.State
	7,  // 17: pb.StateMap.state:type_name -> pb.State
	0,  // 18: pb.AdjudicatorEventBase.Timeout.type:type_name -> pb.AdjudicatorEventBase.TimeoutType
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_sdktypes_proto_init() }
func file_sdktypes_proto_init() {
	if File_sdktypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdktypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Balance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Balances); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAlloc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Allocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjudicatorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjudicatorEventBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgressedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConcludedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdktypes_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjudicatorEventBase_Timeout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdktypes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdktypes_proto_goTypes,
		DependencyIndexes: file_sdktypes_proto_depIdxs,
		EnumInfos:         file_sdktypes_proto_enumTypes,
		MessageInfos:      file_sdktypes_proto_msgTypes,
	}.Build()
	File_sdktypes_proto = out.File
	file_sdktypes_proto_rawDesc = nil
	file_sdktypes_proto_goTypes = nil
	file_sdktypes_proto_depIdxs = nil
}
